version: '3'
services:
  suitecrm:
    build:
      context: 'suite'
      args:
        - 'BACK_END=${BACK_END}'
        - 'USER_ID=${USER_ID}'
        - 'GROUP_ID=${GROUP_ID}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'XDEBUG=${XDEBUG}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_SUITE}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${SUITE_HOST_HTTP_PORT}:80'
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - ${MYSQL_PORT}:3306
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - 'PMA_ARBITRARY=1'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - '${PMA_PORT}:80'
volumes: {}
