    version: '3'
    services:
      mariadb:
        build: './mariadb'
        environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
          - MARIADB_USER=bn_suitecrm
          - MARIADB_DATABASE=bitnami_suitecrm
        volumes:
          - '${DATA_PATH_HOST}:/bitnami/mariadb'
      suitecrm:
        build: './suitecrm'
        ports:
          - '${SUITECRM_HTTP_PORT}:8080'
          - '${SUITECRM_HTTPS_PORT}:8443'
        environment:
          - SUITECRM_DATABASE_HOST=mariadb
          - SUITECRM_DATABASE_PORT_NUMBER=3306
          - SUITECRM_DATABASE_USER=bn_suitecrm
          - SUITECRM_DATABASE_NAME=bitnami_suitecrm
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - '${APP_CODE_PATH_HOST}:/bitnami/suitecrm'
        depends_on:
          - mariadb
    volumes:
      mariadb_data:
        driver: local
      suitecrm_data:
        driver: local